---
- name: Downloads install script
  get_url: url=https://download.clojure.org/install/linux-install-1.9.0.381.sh dest=~/clojure-install-script.sh mode=1755

- name: Runs install script
  shell: "{{ ansible_env.HOME }}/clojure-install-script.sh"
  become_user: root

- name: Removes install script
  file: path=~/clojure-install-script.sh state=absent
