---
- name: Adds emacs ppa
  apt_repository:
    repo: ppa:kelleyk/emacs
  become_user: root

- name: Installs emacs25
  apt: pkg=emacs25 state=latest
  become_user: root

- name: Sets config[1/2] Delete .emacs.d 
  file: path={{ ansible_env.HOME }}/.emacs.d state=absent
- name: Set config[2/2] Bring .emacs.d
  copy: src=../files/.emacs.d dest={{ ansible_env.HOME }}/ 

- name: Adds alias
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    line: "alias em='emacsclient -nw'"


