---
- name: Installs emacs
  apt: pkg=emacs state=latest
  become_user: root

- name: Sets config[1/2] Delete .emacs.d 
  file: path={{ ansible_env.HOME }}/.emacs.d state=absent
- name: Set config[2/2] Bring .emacs.d
  copy: src=.emacs.d dest={{ ansible_env.HOME }}/ 
