---
# use --become-user <your_user> for changes being made upon upon the user
# and don't forget about --ask-sudo-pass
- hosts: all
  tasks:
  - include: misc.yml
    tags: misc

  - include: react-native.yml
    vars:
        nodejs_ppa_path: "{{ ansible_env.HOME }}/nodejs-setup.sh"
    tags: react-native

  - include: docker.yml
    become_user: root
    tags: docker

  - include: clojure.yml
    tags: clojure

  - include: cljsrn.yml
    tags: cljsrn

  - include: emacs.yml 
    tags: emacs
  become: true
