---
- name: NodeJS[1/4] Download shell script for add nodejs PPA
  get_url: 
    url: https://deb.nodesource.com/setup_8.x
    dest: "{{ nodejs_ppa_path }}"
    mode: 0755
  become_user: root
- debug:
    msg: "{{ nodejs_ppa_path }}"

- name: NodeJS[2/4] Add nodejs PPA
  shell: "bash {{ nodejs_ppa_path }}"
  become_user: root

- name: NodeJS[3/4] Delete shell script
  file:
    path: "{{ nodejs_ppa_path }}"
    state: absent

- name: NodeJS[4/4] Install necessary libs
  apt: pkg={{ item }} state=latest
  with_items:
    - nodejs
    - build-essential
    - autoconf
    - automake
    - libtool
    - pkg-config
    - python-setuptools
    - python-dev
    - libssl-dev
  become_user: root

- name: Installs react-native-cli
  npm:
    name: react-native-cli
    state: latest
    global: yes
  become_user: root
